ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'TERRAFORM_VALIDATE_REQUESTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'TERRAFORM_PLAN_REQUESTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'TERRAFORM_APPLY_REQUESTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ANSIBLE_SYNTAX_CHECK_REQUESTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ANSIBLE_CHECK_REQUESTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ANSIBLE_RUN_REQUESTED';

ALTER TYPE "OperationProvider" ADD VALUE IF NOT EXISTS 'INFRASTRUCTURE';

ALTER TYPE "OperationType" ADD VALUE IF NOT EXISTS 'TERRAFORM_VALIDATE';
ALTER TYPE "OperationType" ADD VALUE IF NOT EXISTS 'TERRAFORM_PLAN';
ALTER TYPE "OperationType" ADD VALUE IF NOT EXISTS 'TERRAFORM_APPLY';
ALTER TYPE "OperationType" ADD VALUE IF NOT EXISTS 'ANSIBLE_SYNTAX_CHECK';
ALTER TYPE "OperationType" ADD VALUE IF NOT EXISTS 'ANSIBLE_CHECK';
ALTER TYPE "OperationType" ADD VALUE IF NOT EXISTS 'ANSIBLE_RUN';
