ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'AWS_ECR_IMAGE_BUILD_REQUESTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'AWS_ECR_IMAGE_PUSH_REQUESTED';

ALTER TYPE "OperationType" ADD VALUE IF NOT EXISTS 'AWS_ECR_IMAGE_BUILD';
ALTER TYPE "OperationType" ADD VALUE IF NOT EXISTS 'AWS_ECR_IMAGE_PUSH';
