ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'DOCKER_CONTAINER_START_REQUESTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'DOCKER_CONTAINER_STOP_REQUESTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'DOCKER_CONTAINER_RESTART_REQUESTED';

ALTER TYPE "OperationType" ADD VALUE IF NOT EXISTS 'DOCKER_CONTAINER_START';
ALTER TYPE "OperationType" ADD VALUE IF NOT EXISTS 'DOCKER_CONTAINER_STOP';
ALTER TYPE "OperationType" ADD VALUE IF NOT EXISTS 'DOCKER_CONTAINER_RESTART';
